stages:
  - build
  - test
  - package
build:
  stage: build
  script:
    - mvn compile
test:
  stage: test
  script:
    - mvn test
package:
  stage: package
  script:
    - mvn package
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - target/dist
    expire_in: 4 weeks